<div class="container text-center">
  <h3>Jun Lu Performing Arts Academy</h3><br>
  <div class="row">
    <div class="col-sm-12">
      <div class="well">

        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
          <tr>
            <td width="100%">
            <h3>Mission </h3>
            <p><font class="maintxt">We advocate and promote mutual
            understanding and appreciation through languages of the arts.&nbsp;&nbsp;
            Our programs, through the beautiful arts of motion and sound,
            encourage passion, creativity thinking, and team spirit besides the
            learning of basic and advanced techniques.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <br>
&nbsp;</font></td>
          </tr>
          <tr>
            <td width="100%">
            <h3>About Our Artistic Director</h3>
            <p>
                <img border="0" src="images/jun/lj_jc2r.JPG" width="156" height="231" align="right">Our
                artistic director,&nbsp; Jun
                Lu,&nbsp; is an award-winning choreographer, performing artist and
                dance instructor.&nbsp; In 1988, Ms. Lu won a silver medal in
                the premier national &quot;TaoLi&quot; Cup professional dance competition
                in China and was featured in the CCTV's &quot;The Rising Star&quot;
                program. Since then, Ms. Lu has won many national and
                international gold and silver awards in choreography,
                performance, teaching, and public service. And as an outstanding
                Chinese folk dance artist, Ms. Lu has been invited to tour and
                perform in more than 15 Europe and Asia countries representing
                China. Ms. Lu was also a principle dancer of the famous Chinese
                Youth Dance Troupe and the Singapore People's Association Dance
                Company. Detailed information can be found in her curriculum
                vitae.&nbsp;&nbsp; </p>
                <p>Ms Lu has a rich teaching experience. She has taught dance
                and choreography in the prestigious Beijing Dance Academy, the
                Singapore Nanyang Academy of Fine Arts, the LaSalle-Sia College
                of Arts, the Hongkong Dance Company, the J&amp;L Dance School,
                before found the Jun Lu Performing Arts Academy in California
                .&nbsp; Some of her students have also won awards
                in national and
                international dance competitions.&nbsp; Ms. Lu's unique,
                creative, caring, and effective teaching style was also
                manifested by the &quot;Outstanding Teacher&quot; award she received from
                the Singapore Nanyang Academy of Fine Arts.&nbsp;&nbsp; <img border="0" src="images/jun/daiyu1s.JPG" align="right" width="155" height="240">Ms.Lu's teaching and choreography covers Chinese dance, Ballet,
                Jazz, and Flamenco.&nbsp; In her class, Ms. Lu not only
                emphasizes basic techniques, but also encourages passion and
                creative thinking.&nbsp; </p>

                <p>As an outstanding choreographer, Ms. Lu has choreographed
                more than 100 solo and group dances, among which &quot;The Fan&quot;
                received the &quot;Best Choreography&quot; award at the 1999 Asia-Pacific
                International Dance Competition held&nbsp; in Singapore, &quot;The
                Yellow River&quot; and &quot;The Dance of Singapore&quot; were awarded the gold
                and the silver medals in the &quot;Best Choreography&quot; category at the
                2000 Singapore Youth Festival Dance Contest. Her choreography
                work has been staged in many countries.&nbsp;&nbsp;&nbsp;For instance, &quot;The
                Fan&quot; has been staged many times in Singapore and Japan; &quot;Melody
                of Western China&quot; has been staged in China, Singapore, and the
                United States.&nbsp; </p>
                <p>Here are some commendations in the national media about Ms.
                Lu work:<br>
&nbsp;</p>
                <div align="center">
                  <center>
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="70%" height="76">
                    <tr>
                      <td width="100%" height="76">&quot;...Ms. Lu's solo <i>Poetic
                      Perfection </i>portrays a woman's highly suppressed inner
                      feeling in such a humble and helpless way it captured
                      everyone's heart... She communicated with the audience
                      through dancing and made this highly difficult solo look
                      so elegantly effortless ...&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ---
                      United Morning News (1/4/1997), Singapore</td>
                    </tr>
                  </table>
                  </center>
                </div>
                <div align="center">
                  <center>
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="70%">
                    <tr>
                      <td width="100%"><br>
                      &quot;... while scattering flower pedals, she contemplates the
                      brevity of life and becomes slightly disturbed when she
                      realizes that all things comes to an end eventually... The
                      dancer believes that her art cannot be expressed in any
                      other way than dancing... her simple dignity of movement
                      can fulfill the function of volume of words...&quot;&nbsp;&nbsp;
                      <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; --- The
                      Straits Times (6/13/1997) about her performance of <i>The
                      Falling Flowers</i></td>
                    </tr>
                  </table>
                  </center>
                </div>
                <br><img border="0" src="images/jun/Songs11.JPG" align="right" width="155" height="205">
                <br>
                <p>
                Ms.
                Lu also has held numerous workshops and talks at many arts
                schools,&nbsp; dance companies, and public art promotion events
                in various countries. For instance, in 1998, Ms. Lu held a very
                successful &quot;Dance: from Classical to Modern&quot; workshop in
                Singapore to showcase her choreography with the&nbsp; Singapore
                Hokien Arts &amp; Cultural Troupe; in 2000, she organized a workshop
                &quot;Dance in Society&quot; with the St. Paulo Dance Company in
                Indonesia; in 2002, she was invited by the Young Audience of
                Houston to help develop an education program &quot;Dance and Music of
                China&quot; to cultivate an appreciation of cultural diversity in the
                community.&nbsp;&nbsp;&nbsp;&nbsp; </p>
                <p>Ms. Lu holds dance performance and dance education degrees
                from the prestigious Beijing Dance Academy and the Queensland
                University of Science and Technology. </p>
                <br><br>
                <p align="center"><b>Major Awards:</b><br>
                Silver Medal in Performance [Teens group], the second National TaoLi Cup
                Professional Dance Competition(1988)<br>
                Silver Medal [First place in the women's group] in folk dance performance,
                the third National TaoLi Cup Professional Dance Competition
                (1991)<br>
                The &quot;Mountain Everest&quot; Award from the Chinese Ministry of
                Culture (1991)<br>
                Silver Medal [First place in the women's group] in the 3rd
                Chinese National Dance Competition (1995)<br>
                Best Performance Award in the Beijing Dance Competition (1995)<br>
                &quot;Best Choreography&quot; Award in the Asia-Pacific International
                Dance Competition (1999) <br>
                &quot;Best Performance&quot; Award in the Asia-Pacific International Dance
                Competition (1999) <br>
                Gold Award in Best Choreography in the Singapore Youth Festival
                Dance Contest (2000)<br>
                Silver Award in&nbsp; Best Choreography in the Singapore Youth
                Festival Dance Contest (2000)<br>
                Outstanding teacher award from the Singapore Nanyang Academy of
                Fine Arts (2000)<br>
                ......<br>
                American Dance Awards, <b>Choreographer of the Year</b>, Diamond Choreography Winner(2013)<br>
                American Dance Awards, <b>Choreographer of the Year</b>, Diamond Choreography Winner(2014)<br>
                <b>Choreographer of the Year</b>, KAR National Final (2015)<br>
                <b>Best Choreography</b>, Overseas TaoLi Cup (2016-2017)<br>
                <b>Best Choreography</b>, StarQuest (2018)<br>
                <b>Choreographer of the Year</b>, KAR National Final (2018)<br>
                </p>
                
                <p>&nbsp;
            </td>
          </tr>
        </table>

      </div>
    </div>
  </div>
  <h4>Registration Form and Policy</h4><br>
  <div class="row">
    <div class="col-sm-12">
      <div class="well">
        <a href="http://www.danceinthewind.com/studio/registration2007.pdf">
          Registration Form
        </a>
        |
        <a href="http://www.danceinthewind.com/studio/policy.pdf">
          Academy Policy
        </a>
      </div>
    </div>
  </div>
</div>
